###
# @name registerPartner1
POST http://localhost:3000/partners/register
Content-Type: application/json

{
  "name": "Test Partner 1",
  "email": "testuser1o@example.com",
  "password": "testpassword",
  "company_name": "Test Company"
}

###
# @name loginPartner1
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "testuser1o@example.com",
  "password": "testpassword"
}

###
@tokenPartner1 = {{loginPartner1.response.body.token}}

###
# @name registerCustomer1
POST http://localhost:3000/customers/register
Content-Type: application/json

{
  "name": "Test Customer 2",
  "email": "testcustomer2@example.com",
  "password": "testpassword",
  "address": "123 Test St",
  "phone": "123-456-7890"
}

###
# @name loginCustomer1
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "testcustomer2@example.com",
  "password": "testpassword"
}

###
@tokenCustomer1 = {{loginCustomer1.response.body.token}}

### Listagem pública de todos os eventos
GET http://localhost:3000/events

### Criação do evento pelo parceiro
POST http://localhost:3000/partners/events
Content-Type: application/json
Authorization: Bearer {{tokenPartner1}}

{
  "name": "Test Event 1",
  "description": "This is a test event.",
  "date": "2027-07-01T10:00:00Z",
  "location": "Test Venue"
}
### Listagem dos eventos criados pelo parceiro
GET http://localhost:3000/partners/events
Authorization: Bearer {{tokenPartner1}}

### Listagem dos detalhes do evento criado pelo parceiro
GET http://localhost:3000/partners/events/1
Authorization: Bearer {{tokenPartner1}}

### Criação de tickets para o evento criado pelo parceiro
POST http://localhost:3000/partners/events/1/tickets
Content-Type: application/json
Authorization: Bearer {{tokenPartner1}}

{
  "numTickets": 100,
  "price": 50.00
}
